In [13]:
# x_data = (예습시간, 복습시간)
# t_data = 1 (Pass), 0 (Fail)

import numpy as np

x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7] ])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9, 1)

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape) 

x_data.ndim =  2 , x_data.shape =  (9, 2)
t_data.ndim =  2 , t_data.shape =  (9, 1)


In [14]:
W = np.random.rand(2, 1)  # 2X1 행렬 : 최적화해야할 가중치가 2개이다. # 랜덤하게 선택한다. 
b = np.random.rand(1)     # 바이어스
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.34763287]
 [0.03242803]] , W.shape =  (2, 1) , b =  [0.14121902] , b.shape =  (1,)


In [15]:
# classification 이므로 출력함수로 sigmoid 정의

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [16]:
# 최종출력은 y = sigmoid(Wx+b) 이며, 손실함수는 cross-entropy 로 나타냄
# 아래 수치미분 함수에 사용됨. 

def loss_func(x, t):
    
    delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    return  -np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) )  # 수식을 그대로 표현하면 된다. 

In [17]:
# 수치미분에 대한 내용이다. 
# 차후 상세하게 설명한다. 지금은 미분하는 함수 정도로 이해하고 넘어간다. 
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [18]:
# 최종출력은 y = sigmoid(Wx+b) 이며, 손실함수는 cross-entropy 로 나타냄
# x는 [예습시간, 복습시간] 형태의 벡터이다. 
def error_val(x, t):
    delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    return  -np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) )  

def predict(x):
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    if y > 0.5:
        result = 1  # True
    else:
        result = 0  # False
    
    return y, result

In [19]:
learning_rate = 1e-2  # 1e-2, 1e-3 은 손실함수 값 발산

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b )

for step in  range(80001):  
    
    W -= learning_rate * numerical_derivative(f, W)
    
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial error value =  8.992419305571007 Initial W =  [[0.34763287]
 [0.03242803]] 
 , b =  [0.14121902]
step =  0 error value =  4.754069925091281 W =  [[ 0.17127881]
 [-0.19168412]] , b =  [0.13905476]
step =  400 error value =  2.1840501229330256 W =  [[ 0.43191023]
 [-0.07984603]] , b =  [-2.79812701]
step =  800 error value =  1.5558663016834913 W =  [[ 0.54460192]
 [-0.02273347]] , b =  [-4.37236545]
step =  1200 error value =  1.2607829921138505 W =  [[0.62995495]
 [0.01145653]] , b =  [-5.45514819]
step =  1600 error value =  1.08592034898017 W =  [[0.69916455]
 [0.03609666]] , b =  [-6.28947625]
step =  2000 error value =  0.9680092589946644 W =  [[0.75766611]
 [0.05586027]] , b =  [-6.97478499]
step =  2400 error value =  0.8817201300863329 W =  [[0.80848816]
 [0.0728542 ]] , b =  [-7.56107489]
step =  2800 error value =  0.8149303679298538 W =  [[0.85349379]
 [0.08817854]] , b =  [-8.07687695]
step =  3200 error value =  0.7610967228798089 W =  [[0.89391487]
 [0.10246375]] ,

step =  31200 error value =  0.17177961714426646 W =  [[1.77824018]
 [0.70002512]] , b =  [-20.12369283]
step =  31600 error value =  0.1699196194513431 W =  [[1.78462183]
 [0.70479212]] , b =  [-20.20964419]
step =  32000 error value =  0.16809893085630218 W =  [[1.79093813]
 [0.70950465]] , b =  [-20.29468188]
step =  32400 error value =  0.16631632820771033 W =  [[1.7971904 ]
 [0.71416391]] , b =  [-20.37882487]
step =  32800 error value =  0.16457063837017705 W =  [[1.8033799 ]
 [0.71877106]] , b =  [-20.46209158]
step =  33200 error value =  0.16286073569542567 W =  [[1.80950785]
 [0.72332725]] , b =  [-20.54449984]
step =  33600 error value =  0.1611855396458136 W =  [[1.81557547]
 [0.72783357]] , b =  [-20.62606696]
step =  34000 error value =  0.15954401255934886 W =  [[1.82158389]
 [0.73229109]] , b =  [-20.70680972]
step =  34400 error value =  0.1579351575467129 W =  [[1.82753426]
 [0.73670083]] , b =  [-20.78674443]
step =  34800 error value =  0.15635801651097186 W =  [[1.

step =  62400 error value =  0.09233209884490005 W =  [[2.14411219]
 [0.96577845]] , b =  [-25.00690587]
step =  62800 error value =  0.09178499389018496 W =  [[2.14762983]
 [0.96827428]] , b =  [-25.05350708]
step =  63200 error value =  0.09124428718885051 W =  [[2.15112722]
 [0.97075487]] , b =  [-25.09983489]
step =  63600 error value =  0.09070986774352592 W =  [[2.15460458]
 [0.97322041]] , b =  [-25.14589246]
step =  64000 error value =  0.09018162709934967 W =  [[2.15806215]
 [0.97567106]] , b =  [-25.19168291]
step =  64400 error value =  0.08965945927179474 W =  [[2.16150014]
 [0.97810702]] , b =  [-25.23720928]
step =  64800 error value =  0.0891432606769533 W =  [[2.16491878]
 [0.98052845]] , b =  [-25.28247459]
step =  65200 error value =  0.0886329300641691 W =  [[2.16831827]
 [0.98293553]] , b =  [-25.32748178]
step =  65600 error value =  0.0881283684508921 W =  [[2.17169883]
 [0.98532842]] , b =  [-25.37223376]
step =  66000 error value =  0.08762947905972022 W =  [[2.

In [20]:
test_data = np.array([3, 17]) # (예습, 복습) = (3, 17) => Fail (0)
predict(test_data) 

(array([0.12870842]), 0)

In [21]:
test_data = np.array([5, 8]) # (예습, 복습) = (5, 8) => Fail (0)

predict(test_data) 

(array([0.00098994]), 0)

In [22]:
test_data = np.array([7, 21]) # (예습, 복습) = (7, 21) => Pass (1)

predict(test_data) 

(array([0.99998956]), 1)

In [23]:
test_data = np.array([12, 0])  # (예습, 복습) = (12, 0) => Pass (1)

predict(test_data) 

(array([0.63495507]), 1)